wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: Epochs
      6:
      - 3
    - 1: Loss
      5: 1
      6:
      - 1
      - 3
    - 1: Accuracy
      5: 1
      6:
      - 1
      - 3
    python_version: 3.10.6
    start_time: 1671302204.930801
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 5
